[package]
name = "guile-sys"
version = "0.1.0"
authors = ["Vee Satayamas <vee.sa@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dependencies]

[build-dependencies]
pkg-config = "0.3"
bindgen = "0.54"

